### ISSUE TITLE
Linux version not working

### ISSUE THREAD

**Issue by pethipet** [Paul-Hi/Mango#1]
I did a checkout from
repository 16503bc751d18729fc3e63a102f5274f61e966da

Build was flawless, but it did not work.
Please find attached info from the run  + my configuration glxinfo

![editor_output_linux](https://user-images.githubusercontent.com/12410286/77236109-9ae55a80-6bbb-11ea-848e-fa44b3bb5053.png)

In addtion please find the glxinfo output 

[glxinfo.txt](https://github.com/Paul-Hi/Mango/files/4364040/glxinfo.txt)

**Comment by Paul-Hi** [comment]
Problem should be fixed with commit 5cc8c0d5e93d6866b974d02c3757b33dc6f3d87a.
